# Generated by Django 3.1.6 on 2021-02-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('Кошка', 'Кошка'), ('Собака', 'Собака'), ('Попугай', 'Попугай')], max_length=16, verbose_name='Вид питомца')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('gender', models.CharField(blank=True, choices=[('мальчик', 'мальчик'), ('девочка', 'девочка')], max_length=8, verbose_name='Пол')),
                ('breed', models.CharField(default='Беспородный', max_length=250, verbose_name='Порода')),
                ('color', models.CharField(max_length=128, verbose_name='Окрас')),
                ('avatar', models.ImageField(blank=True, upload_to='images', verbose_name='Фото')),
                ('age', models.SmallIntegerField(default='Неизвестно', verbose_name='Возраст')),
                ('date_of_entry', models.DateField(blank=True, verbose_name='Дата поступления')),
                # ('anonse', models.CharField(blank=True, max_length=250, verbose_name='Коротко о питомце')),
                ('about', models.TextField(blank=True, verbose_name='О питомце')),
            ],
        ),
    ]
