# Generated by Django 3.1.6 on 2021-02-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_of_entry',
            field=models.DateField(verbose_name='Дата поступления'),
        ),
    ]
